### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.nickvision.money#58]
The `home` permission is quite vast.  Why does it need access to the entire home folder? As far as I'm aware, it can access any file through a portal. It doesn't need constant access to a user's whole home folder?

**Comment by nlogozzo** [comment]
The problem comes from creating an account file. The user can specify the portal path of where they want the file to be saved but the `Microsoft.Data.Sqlite` package has trouble creating a new database (account) file from a portal path. Thus, needed `home` permission to give the true path.

See:
https://github.com/NickvisionApps/Denaro/issues/121
https://github.com/NickvisionApps/Denaro/issues/107
and other similar issues throughout the repo.

Please open an other issues on the upstream repo.
